const config = {
    AUTH0_DOMAIN: process.env.AUTH0_DOMAIN,
    API_IDENTIFIER: process.env.API_IDENTIFIER,
    API_AUDIENCE: process.env.API_AUDIENCE,
    API_MANAGEMENT_AUDIENCE: process.env.API_MANAGEMENT_AUDIENCE,
    CLIENT_ID: process.env.CLIENT_ID,
    CLIENT_SECRET: process.env.CLIENT_SECRET,
    AUTH0_CALLBACK_URL: process.env.AUTH0_CALLBACK_URL,
    SECRET_KEY: process.env.SECRET_KEY,
    AUTH0_MANAGEMENT_CLIENT_I: process.env.AUTH0_MANAGEMENT_CLIENT_ID,
    AUTH0_MANAGEMENT_CLIENT_SECRET: process.env.AUTH0_MANAGEMENT_CLIENT_SECRET,
  };

export default config;